project:
  type: website
  output-dir: docs

website:
  title: "DataChaos"
  navbar:
    logo: logosemfundo.png
    background: primary
    search: true
    left:
      - href: index.qmd
        text: " "
        icon: house-fill
      - presentation.qmd
      - sidebar:portfolio
      - contato.qmd
  
  sidebar:
  - id: portfolio
    title: "Portf√≥lio"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - portfolio/Ilustra.qmd
      - portfolio/Mapas.qmd
      - portfolio/Figures.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [minty, styles.scss]
      dark: [minty, styles_dark.scss]
    css: styles.css
    toc: true
    page-layout: full
    grid:
      margin-width: 100px
      body-width: 800px



